frameworkVersion: "1.1.0"

service: ${file(../config.yml):appPrefix}-www

provider:
  name: aws
  runtime: ${file(../config.yml):awsRuntime}
  stage: ${file(../config.yml):awsStage}
  region: ${file(../config.yml):awsRegion}
  profile: ${file(../config.yml):awsProfile}

functions:
  index:
    handler: handler.viewIndex
    events:
      - http:
          path: www
          method: get
          cors: true

package:
  exclude:
    - node_modules/**
    - '!node_modules/lib/**'

plugins:
  - serverless-offline
